
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpp-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_NAME: ${SPRING_DATASOURCE_NAME:-org.postgresql.Driver}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://database:5432/vpp_db}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-vpp_user}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-vpp_pass}
    volumes:
      - ./logs:/logs/vpp

  database:
    image: postgres:15
    container_name: vpp-postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vpp_db}
      POSTGRES_USER: ${POSTGRES_USER:-vpp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vpp_pass}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
    name: vpp_postgres_data